# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b882560568a47e026da52b6b5620682858b1983770e191985116db15e5d574011c2a6fade4d8fde26c8c5f606a0c99378bca78232facd44a9814d80f7e2f7716

test:
  secret_key_base: abe6f9cb13479c299f10107a68f349991d1102e111ba62eba992b29c3f9f5b7d08b298acb9f08d82ec3f495ae90b0120c492b454200e68ddc8167631beec71f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
